# Set up the Rust toolchain.
language: rust

rust:
  - stable
  - nightly

# Allow for occasional compiler breakage on nightly Rust.
matrix:
  allow_failures:
    - rust: nightly

sudo: false
os: linux
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install libgtk-3-dev;
  fi
cache: cargo
script: cargo build --verbose --all